# TODO:
#  cmake_static is generally broken.
#  test_auto_schedule is flaky.

name: Build+Test
on:
  # TODO: not sure if this is the proper set of events/activity-types we want
  pull_request:
    types: [opened, synchronize, reopened, edited, review_requested]

jobs:
  test_halide:
    name: ${{matrix.arch}}-${{matrix.bits}}-${{matrix.halide_os}} llvm-${{matrix.llvm_version}} (${{matrix.build_tool}})
    runs-on: ${{matrix.os}}
    env:
      CC: ${{matrix.cc}}
      CXX: ${{matrix.cxx}}
      LD: ld

    strategy:
      fail-fast: false  # Keep running other jobs even if one fails
      matrix:
        # TODO: this is probably overkill; we probably don't need to build the full
        # matrix (and since we are limited to 8 concurrent tests, it would be
        # useful to prune this a bit).
        arch: [x86]
        bits: [32, 64]
        os: [windows-latest, ubuntu-18.04, macos-latest]
        llvm_version: [8, 9, 10, trunk]
        build_tool: [make, cmake_shared]
        cmake_gen: ["Unix Makefiles"]
        include:
          - llvm_version: 8
            llvm_branch: release/8.x
          - llvm_version: 9
            llvm_branch: release/9.x
          - llvm_version: 10
            llvm_branch: release/10.x
          - llvm_version: trunk
            llvm_branch: master

          - os: macos-latest
            cc: clang
            cxx: clang++
            halide_os: osx

          - os: ubuntu-18.04
            cc: gcc
            cxx: g++
            halide_os: linux

          - os: windows-latest
            cc: cl.exe
            cxx: cl.exe
            halide_os: windows

          - build_tool: cmake_shared
            shared_library: ON
          - build_tool: cmake_static
            shared_library: OFF

        exclude:
          # Don't attempt 32-bit builds for macos
          - os: macos-latest
            bits: 32
          # Don't use make on windows
          - os: windows-latest
            build_tool: make

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'halide'

    - name: Configure Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update

        # Install OpenGL
        # TODO(srj): OpenGL is only needed to build the opengl tests (which we don't even run)...
        sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev

        sudo apt-get -y --force-yes install libjpeg-dev
        sudo apt-get -y --force-yes install libpng-dev
        sudo apt-get -y --force-yes --no-install-recommends install doxygen

    - name: Configure Ubuntu-32
      if: startsWith(matrix.os, 'ubuntu') && matrix.bits == 32
      shell: bash
      run: |
        sudo apt-get install gcc-multilib g++-multilib

    - name: Configure OSX
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install libpng jpeg doxygen

    - name: Configure Env Vars
      shell: bash
      run: |
        # Demangle Windows names, to simplify CMake stuff later
        _ROOT=${GITHUB_WORKSPACE//\\//}
        _TEMP_RAW="${{runner.temp}}"
        _TEMP=${_TEMP_RAW//\\//}

        # This is the trick GitHub Actions uses to allow us to set env vars across all subsequent job steps
        echo ::set-env name=LLVM_INSTALL_DIR::"${_ROOT}/llvm"
        echo ::set-env name=LLVM_CONFIG::"${_ROOT}/llvm/bin/llvm-config"
        echo ::set-env name=HALIDE_SOURCE_DIR::"${_ROOT}/halide"
        echo ::set-env name=HALIDE_BUILD_DIR::"${_ROOT}/halide_build"
        echo ::set-env name=HALIDE_TEMP_DIR::"${_TEMP}"
        echo ::set-env name=PARALLEL_JOBS::"4"
        echo ::set-env name=PYBIND11_PATH::"${_ROOT}/pybind11"

    - name: Install PyBind
      shell: bash
      run: |
        git clone https://github.com/pybind/pybind11.git \
          "${PYBIND11_PATH}" \
          --branch v2.2 \
          --single-branch \
          --depth 1

    - name: Install LLVM
      shell: bash
      run: |
        set -eux

        LLVM_ID="llvm-${{matrix.llvm_version}}-${{matrix.arch}}-${{matrix.bits}}-${{matrix.halide_os}}"

        curl \
          --user llvm_user:${{secrets.LLVM_USER_PASSWORD}} \
          --output ${HALIDE_TEMP_DIR}/llvm-prebuilt.tgz \
          https://buildbot.halide-lang.org/llvm/${LLVM_ID}.tgz

        TAR_FLAGS=
        if [[ ${{matrix.os}} == windows* ]]; then
          # Must use --force-local to avoid tar misinterpreting the : in
          # a Windows pathname as a hostname.
          TAR_FLAGS=" --force-local "
        fi

        mkdir ${LLVM_INSTALL_DIR}
        tar ${TAR_FLAGS} -xvf ${HALIDE_TEMP_DIR}/llvm-prebuilt.tgz -C ${LLVM_INSTALL_DIR} --strip-components=1
        rm -rf ${HALIDE_TEMP_DIR}/llvm-prebuilt.tgz

    - name: Configure Halide (Make)
      if: startsWith(matrix.build_tool, 'make')
      shell: bash
      run: |
        # Configure Make
        mkdir ${HALIDE_BUILD_DIR}

    - name: Configure Halide (CMake)
      if: startsWith(matrix.build_tool, 'cmake')
      shell: bash
      run: |
        # Configure CMake
        mkdir ${HALIDE_BUILD_DIR}

        cmake \
          -D CMAKE_BUILD_TYPE=Release \
          -D LLVM_DIR="${LLVM_INSTALL_DIR}/lib/cmake/llvm" \
          -D HALIDE_REQUIRE_LLVM_VERSION="${{matrix.llvm_version}}0" \
          -D HALIDE_SHARED_LIBRARY=${{matrix.shared_library}} \
          -G "${{matrix.cmake_gen}}" \
          -A "${{matrix.cmake_arch}}" \
          -T "${{matrix.cmake_toolset}}" \
          -S "${HALIDE_SOURCE_DIR}" \
          -B "${HALIDE_BUILD_DIR}"

    - name: Build Halide (Make)
      if: startsWith(matrix.build_tool, 'make')
      shell: bash
      run: |
        # Build Halide
        cd ${HALIDE_BUILD_DIR}

        # make -f ${HALIDE_SOURCE_DIR}/Makefile -j ${PARALLEL_JOBS} distrib build_tests build_python_bindings build_apps
        make -f ${HALIDE_SOURCE_DIR}/Makefile -j ${PARALLEL_JOBS} distrib build_python_bindings

    - name: Build Halide (CMake)
      if: startsWith(matrix.build_tool, 'cmake')
      shell: bash
      run: |
        # Build Halide
        cd ${HALIDE_BUILD_DIR}
        cmake \
          --build ${HALIDE_BUILD_DIR} \
          --config Release \
          -j ${PARALLEL_JOBS} \
          --target all

    - name: Run Tests (Make)
      if: startsWith(matrix.build_tool, 'make')
      shell: bash
      run: |
        # Test Halide
        export TEST_TMPDIR="${HALIDE_TEMP_DIR}"
        cd ${HALIDE_BUILD_DIR}

        make -f ${HALIDE_SOURCE_DIR}/Makefile test_python

        TEST_GROUPS_PARALLEL="python internal correctness error warning generator apps"

        # tutorial has some performance measurements that can be flaky if we run them in parallel
        TEST_GROUPS_SERIAL="performance tutorial"

        # opengl won't work on the buildbots. auto_schedule is just flaky.
        TEST_GROUPS_BROKEN="opengl auto_schedule"

        # Parallel
        for t in ${TEST_GROUPS_PARALLEL}; do
          make -f ${HALIDE_SOURCE_DIR}/Makefile -j ${PARALLEL_JOBS} test_${t}
        done

        # Serial
        for t in ${TEST_GROUPS_SERIAL}; do
          make -f ${HALIDE_SOURCE_DIR}/Makefile -j ${PARALLEL_JOBS} test_$t
        done

    - name: Run Tests (CMake)
      if: startsWith(matrix.build_tool, 'cmake')
      shell: bash
      run: |
        # Test Halide
        TEST_GROUPS_PARALLEL="internal|correctness|error|tutorial|warning|generator"

        # tutorial has some performance measurements that can be flaky if we run them in parallel
        TEST_GROUPS_SERIAL="performance|tutorial"

        # opengl won't work on the buildbots. auto_schedule is just flaky.
        TEST_GROUPS_BROKEN="opengl|auto_schedule"

        export TEST_TMPDIR="${HALIDE_TEMP_DIR}"
        cd ${HALIDE_BUILD_DIR}

        # Parallel
        ctest \
          -j ${PARALLEL_JOBS} \
          -L "${TEST_GROUPS_PARALLEL}" \
          --output-on-failure

        # Serial
        ctest \
          -L "${TEST_GROUPS_SERIAL}" \
          --output-on-failure

